title: QuantEcon
url: 
description: 

timezone: America/Los_Angeles
google_analytics: UA-54984338-2

# baseurl: /quantecon-jekyll-theme/
baseurl: 

sass:
   sass_dir: _sass
   style: :compressed

repository: 

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

collections:
  projects:
  team-members:
    people: true

defaults:
  -
    scope:
      type: "projects"
    values:
      order: 99